# install-hooks.ps1 - Install the harness-kit git pre-commit hook, and bootstrap the
# machine-local Claude settings file when (and only when) this project has no
# lifecycle hooks wired at all. Mirror of install-hooks.sh (same decisions, same
# generated bytes, same exit codes).
#
# Why the pre-commit hook: .harness/ is the source of truth; CLAUDE.md +
# .github/copilot-instructions.md are generated. Claude Code keeps them fresh via a
# Stop hook in .claude/settings.json, but that Stop hook is Claude-Code-specific — it
# does NOT fire for GitHub Copilot, Cursor, or hand-edits. This pre-commit hook is the
# tool-agnostic backstop: any commit that includes stale generated artifacts is
# blocked, regardless of who or what edited .harness/.
#
# Why the settings bootstrap (T-13): a project whose committed .claude/settings.json
# declares NO lifecycle hooks has no working guard, no doc-sync Stop hook and no
# ambient hooks. When that is the case AND no .claude/settings.local.json exists yet,
# this installer writes one from the hook wiring spec (.harness/scripts/hook-spec),
# using the host OS's byte-forms. It never overwrites an existing machine-local file,
# never writes a backup, and never touches .gitignore.
#
# Usage:
#   pwsh -File .harness/scripts/install-hooks.ps1
#
# Exit codes:
#   0  success (pre-commit installed; machine-local settings bootstrapped OR
#      deliberately not touched — the report says which)
#   1  not a git repository (nothing written)
#   3  committed .claude/settings.json exists but is structurally unparseable
#      (nothing written at all — not even the pre-commit hook)
#   4  the hook wiring spec did not yield a complete set of non-empty commands
#      (nothing written to .claude/)
#   5  writing or confirming the machine-local settings file failed. On the WRITE
#      path (step 6) the target is left ABSENT, never half-written; on the terminal
#      CONFIRMATION path (step 7) the rename already succeeded, so the target is
#      left PRESENT-but-unconfirmed and the diagnostic says so and tells you to
#      remove it and re-run.
#
# To disable the pre-commit hook: delete .git/hooks/pre-commit.
# To remove the machine-local hooks: Remove-Item .claude/settings.local.json
#
# WRITE API (pinned): every generated body goes out through
# [System.IO.File]::WriteAllText on a line array joined with "`n" plus ONE explicit
# trailing "`n". Never Set-Content (emits a BOM on Windows PowerShell 5.1) and never
# Out-File (defaults to UTF-16LE); either would break byte-identity with the bash twin
# and the gate's anchored $schema / indent-based settings parsing.

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
# PowerShell 7.4+ turns a NON-ZERO NATIVE EXIT CODE into a terminating error while
# $ErrorActionPreference is Stop. That would pre-empt the designed exit 4 below exactly
# the way `set -e` does in the bash twin, so opt out explicitly. Harmless on older
# hosts, which simply carry an unused variable.
$PSNativeCommandUseErrorActionPreference = $false

# Script lives at .harness/scripts/ — repo root is two levels up.
$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$gitDir = Join-Path $repoRoot ".git"
$scriptsDir = Join-Path $repoRoot ".harness/scripts"
$claudeDir = Join-Path $repoRoot ".claude"
$committedSettings = Join-Path $claudeDir "settings.json"
$localSettings = Join-Path $claudeDir "settings.local.json"
$specPath = Join-Path $scriptsDir "hook-spec.ps1"

if (-not (Test-Path $gitDir)) {
    Write-Error "Not a git repo: $repoRoot has no .git/. Run 'git init' first."
    exit 1
}

function Write-InstallError($message) {
    [Console]::Error.WriteLine($message)
}

# --- Get-SettingsHookState <path> -> absent | unparseable | empty | present ---------
# A deliberately shallow structural probe (no JSON parser): it answers exactly one
# question — does this settings file declare a non-empty lifecycle-hooks block? — and
# it fails SAFE: a misjudgment can only suppress a write, never cause a wrong one.
# Mirrors settings_hook_state in install-hooks.sh step for step.
function Get-SettingsHookState($settingsPath) {
    if (-not (Test-Path -LiteralPath $settingsPath)) { return 'absent' }
    if (-not (Test-Path -LiteralPath $settingsPath -PathType Leaf)) { return 'present' }
    $raw = ''
    try { $raw = [System.IO.File]::ReadAllText($settingsPath) } catch { return 'unparseable' }
    $trimmed = $raw.Trim()
    if ($trimmed.Length -eq 0) { return 'unparseable' }
    if (-not $trimmed.StartsWith('{')) { return 'unparseable' }
    if (-not $trimmed.EndsWith('}')) { return 'unparseable' }
    # The anchor is the QUOTED key, so a prose mention of hooks in a doc string does
    # not match, and an escaped \"hooks\" never matches either.
    $needle = '"hooks"'
    $idx = $raw.IndexOf($needle, [System.StringComparison]::Ordinal)
    if ($idx -lt 0) { return 'empty' }
    $rest = $raw.Substring($idx + $needle.Length).TrimStart()
    if (-not $rest.StartsWith(':')) { return 'empty' }
    $rest = $rest.Substring(1).TrimStart()
    if (-not $rest.StartsWith('{')) { return 'unparseable' }
    $rest = $rest.Substring(1).TrimStart()
    if ($rest.StartsWith('}')) { return 'empty' }
    return 'present'
}

# --- Step 2: probe the committed settings BEFORE writing anything -------------------
# A structurally broken committed settings file means "change nothing" — this is the
# only path on which the pre-commit hook is not installed.
if ((Test-Path -LiteralPath $committedSettings) -and
    (-not (Test-Path -LiteralPath $committedSettings -PathType Leaf))) {
    Write-InstallError "Committed settings path is not a regular file: $committedSettings"
    Write-InstallError "  Nothing was written. Fix the path and re-run."
    exit 3
}
$committedState = Get-SettingsHookState $committedSettings
if ($committedState -eq 'unparseable') {
    Write-InstallError "Committed settings file does not parse structurally: $committedSettings"
    Write-InstallError "  Nothing was written. Fix the file and re-run."
    exit 3
}

# --- Step 3: install the git pre-commit hook (unchanged behavior) -------------------
$hooksDir = Join-Path $gitDir "hooks"
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

$hookPath = Join-Path $hooksDir "pre-commit"

# Line array (NOT a here-string): .gitattributes pins *.ps1 to CRLF, so a here-string
# body would emit a CRLF /bin/sh hook, and WriteAllText would drop the final newline.
# Joining with "`n" plus one explicit trailing "`n" reproduces the bash heredoc's bytes.
$hookLines = @(
    '#!/bin/sh'
    '# harness-kit pre-commit hook.'
    '# Blocks the commit if .harness/ has drifted from CLAUDE.md or .github/copilot-instructions.md.'
    '# Tool-agnostic: catches edits from Claude Code, Copilot, Cursor, or hand-typed.'
    'set -e'
    '_drift=0'
    'if command -v pwsh >/dev/null 2>&1 && [ -f .harness/scripts/harness-sync.ps1 ]; then'
    '    pwsh -File .harness/scripts/harness-sync.ps1 -Check >/dev/null 2>&1 || _drift=1'
    'elif command -v bash >/dev/null 2>&1 && [ -f .harness/scripts/harness-sync.sh ]; then'
    '    bash .harness/scripts/harness-sync.sh --check >/dev/null 2>&1 || _drift=1'
    'else'
    '    echo "harness-kit pre-commit: neither pwsh nor bash found; skipping drift check." >&2'
    '    exit 0'
    'fi'
    'if [ "$_drift" = "1" ]; then'
    '    echo "" >&2'
    '    echo "harness-kit: drift between .harness/ and .claude/." >&2'
    '    echo "  .claude/agents/ and/or .claude/skills/ are stale relative to .harness/." >&2'
    '    echo "" >&2'
    '    echo "  Fix: pwsh -File .harness/scripts/harness-sync.ps1   (Windows)" >&2'
    '    echo "       bash .harness/scripts/harness-sync.sh          (macOS / Linux)" >&2'
    '    echo "  Then: git add .claude/ && git commit ..." >&2'
    '    echo "" >&2'
    '    echo "  Note: edits to .harness/rules/ do NOT need sync (referenced by AI-GUIDE.md, not composed)." >&2'
    '    echo "  Bypass once (NOT recommended): git commit --no-verify" >&2'
    '    exit 1'
    'fi'
)
[System.IO.File]::WriteAllText($hookPath, (($hookLines -join "`n") + "`n"))

if ($IsLinux -or $IsMacOS) {
    & chmod +x $hookPath
    # $PSNativeCommandUseErrorActionPreference = $false above stops PowerShell 7.4+
    # from raising on a non-zero native exit code, so a failing chmod would otherwise
    # pass silently here while the bash twin (chmod under `set -e`) aborts. Mirror the
    # bash behavior explicitly: abort with the child's own status.
    if ($LASTEXITCODE -ne 0) {
        Write-InstallError "Failed to mark $hookPath executable (chmod exited $LASTEXITCODE)."
        exit $LASTEXITCODE
    }
}

Write-Host "Installed pre-commit hook at $hookPath" -ForegroundColor Green
Write-Host "  Runs harness-sync --check before every commit." -ForegroundColor DarkGray
Write-Host "  Disable: Remove-Item $hookPath" -ForegroundColor DarkGray

# --- Step 4: bootstrap decision (first match wins) ----------------------------------
if ($committedState -eq 'present') {
    Write-Host "Committed settings already declares lifecycle hooks - no machine-local file created." -ForegroundColor DarkGray
    exit 0
}
# Keys on PRESENCE alone, never on content: an unparseable local file, a local file
# holding an empty hooks object (the persistent operator opt-out) and a non-regular
# file at that path all land here and are left byte-untouched.
if ((Get-SettingsHookState $localSettings) -ne 'absent') {
    Write-Host "Machine-local settings already present at $localSettings - left byte-untouched, no backup written." -ForegroundColor DarkGray
    exit 0
}

# --- Step 5: query the hook wiring spec ---------------------------------------------
function Invoke-HookSpec {
    param([string[]]$SpecQuery)
    try {
        $out = & pwsh -NoProfile -File $specPath @SpecQuery
    } catch {
        return $null
    }
    if ($LASTEXITCODE -ne 0) { return $null }
    return $out
}

function Stop-OnSpecFailure($what) {
    Write-InstallError "Hook wiring spec did not answer: $what"
    Write-InstallError "  Nothing was written to .claude/. Check $specPath and re-run."
    exit 4
}

if (-not (Test-Path -LiteralPath $specPath -PathType Leaf)) {
    Stop-OnSpecFailure "spec script missing at $specPath"
}

$hostOs = Invoke-HookSpec @('hostos')
if (($null -eq $hostOs) -or [string]::IsNullOrEmpty([string]$hostOs)) { Stop-OnSpecFailure 'hostos' }
$hostOs = [string]$hostOs

$specTools = Invoke-HookSpec @('tools')
if ($null -eq $specTools) { Stop-OnSpecFailure 'tools' }
$specTools = @($specTools | Where-Object { -not [string]::IsNullOrEmpty([string]$_) })
if ($specTools.Count -eq 0) { Stop-OnSpecFailure 'tools (no tool ids)' }

$wired = @()
foreach ($tool in $specTools) {
    $toolName = [string]$tool
    $tEvent = Invoke-HookSpec @('event', $toolName)
    if (($null -eq $tEvent) -or [string]::IsNullOrEmpty([string]$tEvent)) { Stop-OnSpecFailure "event $toolName" }
    $tMatcher = Invoke-HookSpec @('matcher', $toolName)
    if (($null -eq $tMatcher) -or [string]::IsNullOrEmpty([string]$tMatcher)) { Stop-OnSpecFailure "matcher $toolName" }
    $tSemantics = Invoke-HookSpec @('semantics', $toolName)
    if (($null -eq $tSemantics) -or [string]::IsNullOrEmpty([string]$tSemantics)) { Stop-OnSpecFailure "semantics $toolName" }
    $tCommand = Invoke-HookSpec @('command', $toolName, $hostOs)
    if (($null -eq $tCommand) -or [string]::IsNullOrEmpty([string]$tCommand)) { Stop-OnSpecFailure "command $toolName $hostOs" }
    $wired += @{
        tool      = $toolName
        event     = [string]$tEvent
        matcher   = [string]$tMatcher
        semantics = [string]$tSemantics
        command   = [string]$tCommand
    }
}
$nWired = $wired.Count
# ALL FOUR OR NOTHING (design section 10, FC-4). Not `-eq 0`: a spec that ever answered
# with fewer than four ids - one that dropped the destructive-command guard, say -
# would otherwise produce a PARTIAL wiring that still passed the step-7 confirmation
# (which is derived from those same answers) and exited 0 with a green report.
if ($nWired -ne 4) { Stop-OnSpecFailure "tools (expected 4 ids, got $nWired)" }
# ... and FOUR DISTINCT EVENTS. Arity alone counts IDS, not events: four duplicate
# ids (or a mixed set with one repeat) satisfies `-ne 4`, satisfies the step-7 literals
# whenever the destructive-command guard is among them, and satisfies every per-tool check
# (which would compare the same command to itself), so the installer would exit 0
# having wired ONE event instead of four - and would emit duplicate JSON keys. Runs
# AFTER the arity check on purpose: with fewer than 4 ids the operator wants the
# arity diagnostic. `Sort-Object -Unique` is case-insensitive here, which can only
# make this stricter, never looser.
# Built with -f (never `+` around a `-join`: `-join` binds LOOSER than `+`, so
# "a" + $n + ($x -join ' ') without the inner parens would silently re-associate).
$nDistinct = @($wired | ForEach-Object { $_.event } | Sort-Object -Unique).Count
if ($nDistinct -ne 4) {
    $eventList = ($wired | ForEach-Object { $_.event }) -join ' '
    Stop-OnSpecFailure ('tools (expected 4 DISTINCT hook events, got {0}: {1})' -f $nDistinct, $eventList)
}

# --- Step 6: build the body and write it atomically ---------------------------------
# The spec's return values land in the JSON body UNMODIFIED: no substitution, no
# re-quoting, no -replace / .Replace() anywhere on a command value.
$tmpSettings = $localSettings + ".tmp-" + $PID
# STEP 6 diagnostic only: everything below it runs before the rename, so the target
# genuinely never existed. Step 7 has its own handler - do not reuse this one there.
function Stop-OnWriteFailure($what) {
    Remove-Item -LiteralPath $tmpSettings -Force -ErrorAction SilentlyContinue
    Write-InstallError "Failed to write the machine-local settings file: $what"
    Write-InstallError "  $localSettings was left absent - nothing partial was persisted."
    exit 5
}

# The try/catch is what keeps B-8's exit 5 reachable here: an unhandled New-Item
# failure would abort under $ErrorActionPreference = "Stop" with exit 1, which this
# file's header documents as "not a git repository".
try {
    if (-not (Test-Path $claudeDir)) {
        New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
    }
} catch {
    Stop-OnWriteFailure "could not create $claudeDir"
}

$docComment = "Machine-local Claude Code hooks generated by .harness/scripts/install-hooks from the hook wiring spec (.harness/scripts/hook-spec), using this host's byte-forms. Never distributed. Remove this file to drop the hooks; re-run the installer to recreate it. The installer never overwrites an existing copy."
$docSemantics = "Stop, UserPromptSubmit and SessionStart are fail-open: a missing or unreachable script exits 0 silently. PreToolUse is fail-CLOSED: it carries no exit-0 fallback, so a missing guard blocks the Bash tool call rather than silently disarming the destructive-command guardrail. To keep every hook off permanently, leave this file in place with an empty hooks object - the installer never overwrites an existing file. See .harness/rules/75-safety-hook.md."

$body = [System.Collections.Generic.List[string]]::new()
$body.Add('{')
$body.Add('  "$schema": "https://json.schemastore.org/claude-code-settings.json",')
$body.Add('  "_comment": "' + $docComment + '",')
$body.Add('  "_hook_semantics": "' + $docSemantics + '",')
$body.Add('  "hooks": {')
for ($i = 0; $i -lt $nWired; $i++) {
    $body.Add('    "' + $wired[$i].event + '": [')
    $body.Add('      {')
    if ($wired[$i].matcher -ne 'none') {
        $body.Add('        "matcher": "' + $wired[$i].matcher + '",')
    }
    $body.Add('        "hooks": [')
    $body.Add('          {')
    $body.Add('            "type": "command",')
    $body.Add('            "command": "' + $wired[$i].command + '"')
    $body.Add('          }')
    $body.Add('        ]')
    $body.Add('      }')
    if ($i -eq ($nWired - 1)) { $body.Add('    ]') } else { $body.Add('    ],') }
}
$body.Add('  }')
$body.Add('}')

try {
    [System.IO.File]::WriteAllText($tmpSettings, (($body.ToArray() -join "`n") + "`n"))
} catch {
    Stop-OnWriteFailure "could not write $tmpSettings"
}
try {
    Move-Item -LiteralPath $tmpSettings -Destination $localSettings -Force
} catch {
    Stop-OnWriteFailure "could not move $tmpSettings into place"
}

# --- Step 7: terminal confirmation — re-read FROM DISK, never the in-memory body ----
# STEP 7 diagnostic: these misses happen AFTER the rename succeeded, so the target IS
# present and step 6's "left absent" wording would be a lie. Separate handler, per
# design section 6 (step 6 = target absent; step 7 = stderr, exit 5, no success line).
function Stop-OnConfirmFailure($what) {
    Write-InstallError "Machine-local settings failed terminal confirmation: $what"
    Write-InstallError "  $localSettings is present but was NOT confirmed complete."
    Write-InstallError "  Remove it and re-run: Remove-Item $localSettings"
    exit 5
}
$confirm = ''
try { $confirm = [System.IO.File]::ReadAllText($localSettings) } catch { $confirm = '' }
if ([string]::IsNullOrEmpty($confirm)) { Stop-OnConfirmFailure "the file is empty or unreadable after the write" }
# The two LITERAL confirmations the design pins. They are deliberately hard-coded and
# deliberately kept ALONGSIDE the per-tool checks below: those are derived from the
# spec's own answers, so on their own they prove only that the file contains whatever
# the spec said. These two prove the destructive-command guard's event and matcher
# specifically reached disk.
if ($confirm.IndexOf('"PreToolUse"', [System.StringComparison]::Ordinal) -lt 0) {
    Stop-OnConfirmFailure 'the literal "PreToolUse" event is missing on disk'
}
if ($confirm.IndexOf('"matcher": "Bash"', [System.StringComparison]::Ordinal) -lt 0) {
    Stop-OnConfirmFailure 'the literal "matcher": "Bash" is missing on disk'
}
for ($i = 0; $i -lt $nWired; $i++) {
    if ($confirm.IndexOf('"' + $wired[$i].event + '": [', [System.StringComparison]::Ordinal) -lt 0) {
        Stop-OnConfirmFailure ("event " + $wired[$i].event + " is missing on disk")
    }
    if ($wired[$i].matcher -ne 'none') {
        if ($confirm.IndexOf('"matcher": "' + $wired[$i].matcher + '"', [System.StringComparison]::Ordinal) -lt 0) {
            Stop-OnConfirmFailure ("matcher " + $wired[$i].matcher + " is missing on disk")
        }
    }
    if ($confirm.IndexOf($wired[$i].command, [System.StringComparison]::Ordinal) -lt 0) {
        Stop-OnConfirmFailure ("the " + $wired[$i].tool + " command is missing on disk")
    }
}

# --- Step 8: the report (visible, reversible, correctly classified) -----------------
Write-Host "Created machine-local Claude settings at $localSettings" -ForegroundColor Green
Write-Host "  Wired $nWired lifecycle hooks from the hook wiring spec ($hostOs byte-forms):" -ForegroundColor DarkGray
for ($i = 0; $i -lt $nWired; $i++) {
    Write-Host ("    {0,-16} -> {1,-14} ({2})" -f $wired[$i].event, $wired[$i].tool, $wired[$i].semantics) -ForegroundColor DarkGray
}
Write-Host "  Remove: Remove-Item $localSettings" -ForegroundColor DarkGray
Write-Host "  This file is machine-local: it is never distributed, and it belongs in .gitignore" -ForegroundColor DarkGray
Write-Host "  if this project tracks its .claude/ directory. The installer changes no ignore rules." -ForegroundColor DarkGray
