/**
 * install-hooks — install the harness-kit git pre-commit hook, and bootstrap the
 * machine-local Claude settings file when (and only when) this project has no
 * lifecycle hooks wired at all. TypeScript port (v2 migration, stage 3).
 *
 * Why the pre-commit hook: `.harness/` is the source of truth; CLAUDE.md and
 * .github/copilot-instructions.md are generated. Claude Code keeps them fresh via a
 * Stop hook, but that hook is Claude-Code-specific — it does NOT fire for Copilot,
 * Cursor, or hand-edits. The pre-commit hook is the tool-agnostic backstop.
 *
 * Why the settings bootstrap: a project whose committed settings declares NO lifecycle
 * hooks has no working guard, no doc-sync Stop hook and no ambient hooks. When that is
 * the case AND no machine-local file exists, this writes one from the hook wiring spec
 * using the host OS's byte-forms. It never overwrites an existing machine-local file,
 * never writes a backup, and never touches .gitignore.
 *
 * The spec is now IMPORTED rather than shelled out to. The bash original spawned
 * `bash hook-spec.sh` seventeen times per run (1 hostos + 1 tools + 4 x 4 per-tool);
 * this reads the same single source of truth in-process. The spec's values still land
 * in the JSON body UNMODIFIED — no substitution, no re-quoting anywhere on a command.
 *
 * Exit codes (unchanged from the shell twin):
 *   0  success — pre-commit installed; machine-local settings bootstrapped OR
 *      deliberately not touched (the report says which)
 *   1  not a git repository (nothing written)
 *   3  committed settings exists but is structurally unparseable (nothing written)
 *   4  the hook wiring spec did not yield a complete set of non-empty commands
 *   5  writing or confirming the machine-local settings file failed. On the WRITE path
 *      the target is left ABSENT, never half-written; on the terminal CONFIRMATION path
 *      the rename already succeeded, so it is left PRESENT-but-unconfirmed and the
 *      diagnostic says so.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { TOOLS, EVENTS, matcherOf, semanticsOf, commandOf, type Tool } from './hook-spec';

/** The pre-commit hook body. Byte-identical to the shell twin's heredoc. */
const PRE_COMMIT_BODY = `#!/bin/sh
# harness-kit pre-commit hook.
# Blocks the commit if .harness/ has drifted from CLAUDE.md or .github/copilot-instructions.md.
# Tool-agnostic: catches edits from Claude Code, Copilot, Cursor, or hand-typed.
set -e
_drift=0
if command -v bash >/dev/null 2>&1 && [ -f .harness/scripts/harness-sync.sh ]; then
    bash .harness/scripts/harness-sync.sh --check >/dev/null 2>&1 || _drift=1
else
    echo "harness-kit pre-commit: bash not found; skipping drift check." >&2
    exit 0
fi
if [ "$_drift" = "1" ]; then
    echo "" >&2
    echo "harness-kit: drift between .harness/ and .claude/." >&2
    echo "  .claude/agents/ and/or .claude/skills/ are stale relative to .harness/." >&2
    echo "" >&2
    echo "  Fix: bash .harness/scripts/harness-sync.sh" >&2
    echo "  Then: git add .claude/ && git commit ..." >&2
    echo "" >&2
    echo "  Note: edits to .harness/rules/ do NOT need sync (referenced by AI-GUIDE.md, not composed)." >&2
    echo "  Bypass once (NOT recommended): git commit --no-verify" >&2
    exit 1
fi
`;

const DOC_COMMENT =
  'Machine-local Claude Code hooks generated by .harness/scripts/install-hooks from the hook wiring spec ' +
  "(.harness/scripts/hook-spec), using this host's byte-forms. Never distributed. Remove this file to drop " +
  'the hooks; re-run the installer to recreate it. The installer never overwrites an existing copy.';

const DOC_SEMANTICS =
  'Stop, UserPromptSubmit and SessionStart are fail-open: a missing or unreachable script exits 0 silently. ' +
  'PreToolUse is fail-CLOSED: it carries no exit-0 fallback, so a missing guard blocks the Bash tool call rather ' +
  'than silently disarming the destructive-command guardrail. To keep every hook off permanently, leave this file ' +
  'in place with an empty hooks object - the installer never overwrites an existing file. ' +
  'See .harness/rules/75-safety-hook.md.';

export type HookState = 'absent' | 'unparseable' | 'empty' | 'present';

/**
 * A deliberately shallow structural probe answering exactly one question: does this
 * settings file declare a non-empty lifecycle-hooks block?
 *
 * It fails SAFE — a misjudgment can only suppress a write, never cause a wrong one.
 * The `"hooks"` anchor is the QUOTED key, so a prose mention in a doc string does not
 * match, and an escaped `\\"hooks\\"` never matches either (the byte before `hooks` is
 * a backslash, not a quote).
 */
export function settingsHookState(p: string): HookState {
  // `lstat` throwing means the shell's `[ ! -e ] && [ ! -L ]` — nothing there at all,
  // not even a dangling symlink.
  try {
    fs.lstatSync(p);
  } catch {
    return 'absent';
  }
  // `stat` follows symlinks, matching the shell's `[ ! -f ]`. A directory or a dangling
  // symlink lands here: report `present`, read nothing, write nothing.
  try {
    if (!fs.statSync(p).isFile()) return 'present';
  } catch {
    return 'present';
  }
  let content: string;
  try {
    content = fs.readFileSync(p, 'utf8');
  } catch {
    content = '';
  }
  const squeezed = content.replace(/\s/g, '');
  if (squeezed === '') return 'unparseable';
  if (!squeezed.startsWith('{') || !squeezed.endsWith('}')) return 'unparseable';
  const at = content.indexOf('"hooks"');
  if (at === -1) return 'empty';
  let rest = content.slice(at + '"hooks"'.length).replace(/^\s+/, '');
  if (!rest.startsWith(':')) return 'empty';
  rest = rest.slice(1).replace(/^\s+/, '');
  if (!rest.startsWith('{')) return 'unparseable';
  rest = rest.slice(1).replace(/^\s+/, '');
  return rest.startsWith('}') ? 'empty' : 'present';
}

interface Wiring {
  tool: Tool;
  event: string;
  matcher: string;
  semantics: string;
  command: string;
}

class ExitError extends Error {
  constructor(
    readonly code: number,
    readonly lines: string[],
  ) {
    super(lines.join('\n'));
  }
}

const fail = (code: number, ...lines: string[]): never => {
  throw new ExitError(code, lines);
};

/**
 * Read the wiring from the spec.
 *
 * The ALL-FOUR-OR-NOTHING and FOUR-DISTINCT-EVENTS invariants are kept even though the
 * spec is now a typed import. They are not redundant: a future edit that dropped a tool,
 * or duplicated an event, would otherwise produce a PARTIAL wiring that still passes the
 * terminal confirmation (derived from those same answers) and exits 0 with a green report.
 */
function readWiring(): { wiring: Wiring[] } {
  const wiring: Wiring[] = TOOLS.map((tool) => ({
    tool,
    event: EVENTS[tool],
    matcher: matcherOf(tool),
    semantics: semanticsOf(tool),
    command: commandOf(tool),
  }));

  for (const w of wiring) {
    if (!w.event) fail(4, `Hook wiring spec did not answer: event ${w.tool} (empty answer)`);
    if (!w.matcher) fail(4, `Hook wiring spec did not answer: matcher ${w.tool} (empty answer)`);
    if (!w.semantics) fail(4, `Hook wiring spec did not answer: semantics ${w.tool} (empty answer)`);
    if (!w.command) fail(4, `Hook wiring spec did not answer: command ${w.tool} (empty answer)`);
  }

  if (wiring.length !== 4) {
    fail(4, `Hook wiring spec did not answer: tools (expected 4 ids, got ${wiring.length})`);
  }
  const distinct = new Set(wiring.map((w) => w.event));
  if (distinct.size !== 4) {
    fail(
      4,
      `Hook wiring spec did not answer: tools (expected 4 DISTINCT hook events, got ${distinct.size}: ` +
        `${wiring.map((w) => w.event).join(' ')})`,
    );
  }
  return { wiring };
}

/** Build the settings body. Spec values are interpolated verbatim, never re-quoted. */
export function buildSettingsBody(wiring: readonly Wiring[]): string {
  const body: string[] = [
    '{',
    '  "$schema": "https://json.schemastore.org/claude-code-settings.json",',
    `  "_comment": "${DOC_COMMENT}",`,
    `  "_hook_semantics": "${DOC_SEMANTICS}",`,
    '  "hooks": {',
  ];
  wiring.forEach((w, i) => {
    body.push(`    "${w.event}": [`, '      {');
    if (w.matcher !== 'none') body.push(`        "matcher": "${w.matcher}",`);
    body.push('        "hooks": [', '          {', '            "type": "command",', `            "command": "${w.command}"`, '          }', '        ]', '      }');
    body.push(i === wiring.length - 1 ? '    ]' : '    ],');
  });
  body.push('  }', '}');
  return `${body.join('\n')}\n`;
}

export function run(repoRoot: string, out: (s: string) => void, err: (s: string) => void): number {
  const gitDir = path.join(repoRoot, '.git');
  const committedSettings = path.join(repoRoot, '.claude', 'settings.json');
  const localSettings = path.join(repoRoot, '.claude', 'settings.local.json');

  if (!fs.existsSync(gitDir) || !fs.statSync(gitDir).isDirectory()) {
    err(`Not a git repo: ${repoRoot} has no .git/. Run 'git init' first.`);
    return 1;
  }

  try {
    // --- Step 2: probe the committed settings BEFORE writing anything ---
    // A structurally broken committed settings file means "change nothing" — the only
    // path on which the pre-commit hook is not installed.
    let committedExists = true;
    try {
      fs.lstatSync(committedSettings);
    } catch {
      committedExists = false;
    }
    if (committedExists && !fs.statSync(committedSettings).isFile()) {
      err(`Committed settings path is not a regular file: ${committedSettings}`);
      err('  Nothing was written. Fix the path and re-run.');
      return 3;
    }
    const committedState = settingsHookState(committedSettings);
    if (committedState === 'unparseable') {
      err(`Committed settings file does not parse structurally: ${committedSettings}`);
      err('  Nothing was written. Fix the file and re-run.');
      return 3;
    }

    // --- Step 3: install the git pre-commit hook ---
    const hooksDir = path.join(gitDir, 'hooks');
    fs.mkdirSync(hooksDir, { recursive: true });
    const hookPath = path.join(hooksDir, 'pre-commit');
    fs.writeFileSync(hookPath, PRE_COMMIT_BODY);
    fs.chmodSync(hookPath, 0o755);
    out(`Installed pre-commit hook at ${hookPath}`);
    out('  Runs harness-sync --check before every commit.');
    out(`  Disable: rm ${hookPath}`);

    // --- Step 4: bootstrap decision (first match wins) ---
    if (committedState === 'present') {
      out('Committed settings already declares lifecycle hooks - no machine-local file created.');
      return 0;
    }
    // Keys on PRESENCE alone, never on content: an unparseable local file, one holding an
    // empty hooks object (the persistent operator opt-out) and a non-regular file at that
    // path all land here and are left byte-untouched.
    if (settingsHookState(localSettings) !== 'absent') {
      out(`Machine-local settings already present at ${localSettings} - left byte-untouched, no backup written.`);
      return 0;
    }

    // --- Step 5: read the hook wiring spec ---
    const { wiring } = readWiring();

    // --- Step 6: build the body and write it atomically ---
    const tmp = `${localSettings}.tmp-${process.pid}`;
    try {
      fs.mkdirSync(path.join(repoRoot, '.claude'), { recursive: true });
      fs.writeFileSync(tmp, buildSettingsBody(wiring));
      fs.renameSync(tmp, localSettings);
    } catch (e) {
      try {
        fs.unlinkSync(tmp);
      } catch {
        /* already gone */
      }
      err(`Failed to write the machine-local settings file: ${String(e)}`);
      err(`  ${localSettings} was left absent - nothing partial was persisted.`);
      return 5;
    }

    // --- Step 7: terminal confirmation — re-read FROM DISK, never the in-memory body ---
    const confirmFailed = (why: string): number => {
      err(`Machine-local settings failed terminal confirmation: ${why}`);
      err(`  ${localSettings} is present but was NOT confirmed complete.`);
      err(`  Remove it and re-run: rm ${localSettings}`);
      return 5;
    };
    let onDisk = '';
    try {
      onDisk = fs.readFileSync(localSettings, 'utf8');
    } catch {
      onDisk = '';
    }
    if (onDisk === '') return confirmFailed('the file is empty or unreadable after the write');
    // The two LITERAL confirmations, deliberately hard-coded and deliberately kept
    // alongside the per-tool checks below: those are derived from the spec's own answers,
    // so alone they prove only that the file contains whatever the spec said. These two
    // prove the destructive-command guard's event and matcher specifically reached disk.
    if (!onDisk.includes('"PreToolUse"')) return confirmFailed('the literal "PreToolUse" event is missing on disk');
    if (!onDisk.includes('"matcher": "Bash"')) {
      return confirmFailed('the literal "matcher": "Bash" is missing on disk');
    }
    for (const w of wiring) {
      if (!onDisk.includes(`"${w.event}": [`)) return confirmFailed(`event ${w.event} is missing on disk`);
      if (w.matcher !== 'none' && !onDisk.includes(`"matcher": "${w.matcher}"`)) {
        return confirmFailed(`matcher ${w.matcher} is missing on disk`);
      }
      if (!onDisk.includes(w.command)) return confirmFailed(`the ${w.tool} command is missing on disk`);
    }

    // --- Step 8: the report (visible, reversible, correctly classified) ---
    out(`Created machine-local Claude settings at ${localSettings}`);
    out(`  Wired ${wiring.length} lifecycle hooks from the hook wiring spec:`);
    for (const w of wiring) {
      out(`    ${w.event.padEnd(16)} -> ${w.tool.padEnd(14)} (${w.semantics})`);
    }
    out(`  Remove: rm ${localSettings}`);
    out('  This file is machine-local: it is never distributed, and it belongs in .gitignore');
    out('  if this project tracks its .claude/ directory. The installer changes no ignore rules.');
    return 0;
  } catch (e) {
    if (e instanceof ExitError) {
      for (const line of e.lines) err(line);
      err(`  Nothing was written to .claude/. Check the hook wiring spec and re-run.`);
      return e.code;
    }
    throw e;
  }
}

if (require.main === module) {
  // Script lives at .harness/scripts/ — repo root is two levels up.
  const root = path.resolve(__dirname, '../..');
  const code = run(
    root,
    (s) => process.stdout.write(`${s}\n`),
    (s) => process.stderr.write(`${s}\n`),
  );
  process.exit(code);
}
